package model;
// Generated 13.12.2010 21:38:33 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Schuzka generated by hbm2java
 */
public class Schuzka implements java.io.Serializable {

	private Integer id;
	private int druhAkce;
	private int idAkce;
	private int druhSchuzky;
	private String misto;
	private Date termin;
	private int poradi;

	public Schuzka() {
	}

	public Schuzka(int druhAkce, int idAkce, int druhSchuzky, String misto, Date termin, int poradi) {
		this.druhAkce = druhAkce;
		this.idAkce = idAkce;
		this.druhSchuzky = druhSchuzky;
		this.misto = misto;
		this.termin = termin;
		this.poradi = poradi;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getDruhAkce() {
		return this.druhAkce;
	}

	public void setDruhAkce(int druhAkce) {
		this.druhAkce = druhAkce;
	}

	public int getIdAkce() {
		return this.idAkce;
	}

	public void setIdAkce(int idAkce) {
		this.idAkce = idAkce;
	}

	public int getDruhSchuzky() {
		return this.druhSchuzky;
	}

	public void setDruhSchuzky(int druhSchuzky) {
		this.druhSchuzky = druhSchuzky;
	}

	public String getMisto() {
		return this.misto;
	}

	public void setMisto(String misto) {
		this.misto = misto;
	}

	public Date getTermin() {
		return this.termin;
	}

	public void setTermin(Date termin) {
		this.termin = termin;
	}

	public int getPoradi() {
		return this.poradi;
	}

	public void setPoradi(int poradi) {
		this.poradi = poradi;
	}
}
