package model;
// Generated 13.12.2010 21:38:33 by Hibernate Tools 3.2.1.GA

/**
 * Ubytovani generated by hbm2java
 */
public class Ubytovani implements java.io.Serializable {

	private Integer id;
	private String nazev;

	public Ubytovani() {
	}

	public Ubytovani(String nazev) {
		this.nazev = nazev;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNazev() {
		return this.nazev;
	}

	public void setNazev(String nazev) {
		this.nazev = nazev;
	}
}
