package model;
// Generated 13.12.2010 21:38:33 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Ukol generated by hbm2java
 */
public class Ukol implements java.io.Serializable {

	private Integer id;
	private int idSchuzka;
	private int idUzivatel;
	private Date termin;
	private String zadani;
	private boolean splneno;

	public Ukol() {
	}

	public Ukol(int idSchuzka, int idUzivatel, Date termin, String zadani, boolean splneno) {
		this.idSchuzka = idSchuzka;
		this.idUzivatel = idUzivatel;
		this.termin = termin;
		this.zadani = zadani;
		this.splneno = splneno;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdSchuzka() {
		return this.idSchuzka;
	}

	public void setIdSchuzka(int idSchuzka) {
		this.idSchuzka = idSchuzka;
	}

	public int getIdUzivatel() {
		return this.idUzivatel;
	}

	public void setIdUzivatel(int idUzivatel) {
		this.idUzivatel = idUzivatel;
	}

	public Date getTermin() {
		return this.termin;
	}

	public void setTermin(Date termin) {
		this.termin = termin;
	}

	public String getZadani() {
		return this.zadani;
	}

	public void setZadani(String zadani) {
		this.zadani = zadani;
	}

	public boolean isSplneno() {
		return this.splneno;
	}

	public void setSplneno(boolean splneno) {
		this.splneno = splneno;
	}
}
