package model;
// Generated 13.12.2010 21:38:33 by Hibernate Tools 3.2.1.GA



/**
 * Uzivatel generated by hbm2java
 */
public class Uzivatel  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String heslo;
     private String jmeno;
     private String email;
     private int telefon;
     private int roleId;

    public Uzivatel() {
    }

    public Uzivatel(String login, String heslo, String jmeno, String email, int telefon, int roleId) {
       this.login = login;
       this.heslo = heslo;
       this.jmeno = jmeno;
       this.email = email;
       this.telefon = telefon;
       this.roleId = roleId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getHeslo() {
        return this.heslo;
    }

    public void setHeslo(String heslo) {
        this.heslo = heslo;
    }
    public String getJmeno() {
        return this.jmeno;
    }
    
    public void setJmeno(String jmeno) {
        this.jmeno = jmeno;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(int telefon) {
        this.telefon = telefon;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }




}


