package model;
// Generated 13.12.2010 21:38:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * VicedenniAkce generated by hbm2java
 */
public class VicedenniAkce  implements java.io.Serializable {


     private Integer id;
     private String misto;
     private String termin;
     private int cena;
     private Date casOdjezdu;
     private Date casNavratu;
     private int ubytovani;

    public VicedenniAkce() {
    }

    public VicedenniAkce(String misto, String termin, int cena, Date casOdjezdu, Date casNavratu, int ubytovani) {
       this.misto = misto;
       this.termin = termin;
       this.cena = cena;
       this.casOdjezdu = casOdjezdu;
       this.casNavratu = casNavratu;
       this.ubytovani = ubytovani;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMisto() {
        return this.misto;
    }
    
    public void setMisto(String misto) {
        this.misto = misto;
    }
    public String getTermin() {
        return this.termin;
    }
    
    public void setTermin(String termin) {
        this.termin = termin;
    }
    public int getCena() {
        return this.cena;
    }
    
    public void setCena(int cena) {
        this.cena = cena;
    }
    public Date getCasOdjezdu() {
        return this.casOdjezdu;
    }
    
    public void setCasOdjezdu(Date casOdjezdu) {
        this.casOdjezdu = casOdjezdu;
    }
    public Date getCasNavratu() {
        return this.casNavratu;
    }
    
    public void setCasNavratu(Date casNavratu) {
        this.casNavratu = casNavratu;
    }
    public int getUbytovani() {
        return this.ubytovani;
    }
    
    public void setUbytovani(int ubytovani) {
        this.ubytovani = ubytovani;
    }




}


